# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "GCDS Hugo Variant"
license = "MIT"
licenselink = "https://github.com/gccloudone/gcds-hugo/blob/main/LICENSE.md"
description = "GC Design System components are user interface building blocks that address different user objectives."
homepage = "https://github.com/gccloudone/gcds-hugo"
min_version = "0.126.3"

tags = [
  "government",
  "gcds",
  "multilingual",
]

features = [
  "Accessibility",
  "Multilingual",
  "Search",
]

[author]
  name = "Aurora"
  homepage = "https://aurora.gccloudone.ca"

[original]
author = "Canadian Digital Services"
homepage = "https://design-system.alpha.canada.ca/"
repo = "https://github.com/cds-snc/gcds-components"
